# Tomcat
server:
  port: 9205

# Spring
spring:
  application:
    # 应用名称
    name: ruoyi-crawler
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml

--- # 自定义配置
crawlab:
  token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzY5YjY0ZTRmYThmODYwNjAzMTUyOCIsIm5iZiI6MTcwMzQyMDExOCwidXNlcm5hbWUiOiJhZG1pbiJ9.WSIQdrjQPHKkqo-2Rsn5gSewtbcX5XYTqP9CSKJC-EQ'
