# Tomcat
server:
  port: 9207

# Spring
spring:
  application:
    # 应用名称
    name: ruoyi-manage
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
    stream:
      function:
        # 重点配置 与 binding 名与消费者对应
        definition: delay;websocket;
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml

--- # HanLP 配置
hanlp:
  url: "https://www.hanlp.com/api"
  #  url: https://www.hanlp.com/hanlp/v21/redirect
  token: "NDE4OEBiYnMuaGFubHAuY29tOjBBa0hKY2p3YVhUelVoRFY="

--- # elasticsearch 功能配置
easy-es:
  # 是否开启EE自动配置
  enable: false
  # es连接地址+端口 格式必须为ip:port,如果是集群则可用逗号隔开
  address: @es.address@
  # 默认为http
  schema: http
  banner: false

--- # Dubbo 配置
dubbo:
  protocol:
    name: dubbo
    port: -1
    payload: 104857600 #10MB
  consumer:
    timeout: 200000

--- # rabbitmq 配置
spring:
  rabbitmq:
    host: localhost
    port: 5672
    # 虚拟主机必须提前在mq山创建好
    virtual-host: /
    username: admin
    password: admin
  cloud:
    stream:
      rabbit:
        bindings:
          #          延迟交换机需要安装delayed-message插件
          delay-in-0:
            consumer:
              delayedExchange: true
          delay-out-0:
            producer:
              delayedExchange: true
          websocket-in-0:
            consumer:
              delayedExchange: true
          websocket-out-0:
            producer:
              delayedExchange: true
      bindings:
        #        最好将不同交换机和队列的destination和group分开，否则会混乱
        delay-in-0:
          destination: delay.exchange.cloud
          content-type: application/json
          group: delay-group
          binder: rabbit
        delay-out-0:
          destination: delay.exchange.cloud
          content-type: application/json
          group: delay-group
          binder: rabbit
        websocket-in-0:
          destination: websocket.exchange.cloud
          content-type: application/json
          group: websocket-group
          binder: rabbit
        websocket-out-0:
          destination: websocket.exchange.cloud
          content-type: application/json
          group: websocket-group
          binder: rabbit
